CSharpSpaceXApp/Controllers/FileController.cs
using System.Collections.Generic;
using System.IO;
using CSharpSpaceXApp.Models;
using CSharpSpaceXApp.Services.Contracts;
using iTextSharp.text;
using Microsoft.AspNetCore.Mvc;

/// <summary>
/// FileController takes the API information about launches and exports it to a downloadable PDF file.
/// </summary>

namespace CSharpSpaceXApp.Controllers
{
    public class FileController : Controller
    {
        private ISpaceXApiService fileService;
        private IGitHubService gitHubService;

        public FileController(ISpaceXApiService fileService, IGitHubService gitHubService)
        {
            this.fileService = fileService;
            this.gitHubService = gitHubService;
        }


        [HttpPost]
        
        public FileResult ExportUpcoming()
        {
            using (MemoryStream stream = new MemoryStream())
            {
                string title = "Upcoming launches SpaceX";
                Document pdfDoc = fileService.CreatePDF(stream, title);

                List<Launch> upcomingLaunches = gitHubService.GetUpcomingFlights(Constants.Constants.UPCOMING_LAUNCHES);

                fileService.AddLaunchesToPdf(pdfDoc, upcomingLaunches);

                pdfDoc.Close();
                return File(stream.ToArray(), "application/pdf", "Upcoming.pdf");
            }
        }

        [HttpPost]
        
        public FileResult ExportLatestLaunch()
        {
            using (MemoryStream stream = new MemoryStream())

            {
                string title = "Latest launch SpaceX";
                Document pdfDoc = fileService.CreatePDF(stream, title);

                Launch latestLaunch = gitHubService.GetLatestLaunch(Constants.Constants.LATEST_LAUNCHES);

                pdfDoc.Add(new Paragraph(latestLaunch.ToString()));
                pdfDoc.Close();
                return File(stream.ToArray(), "application/pdf", "LatestLaunch.pdf");
            }
        }

        [HttpPost]
        
        public FileResult ExportNextLaunch()
        {
            using (MemoryStream stream = new MemoryStream())

            {
                string title = "Next launch SpaceX";
                Document pdfDoc = fileService.CreatePDF(stream, title);

                Launch nextLaunch = gitHubService.GetLatestLaunch(Constants.Constants.NEXT_LAUNCHES);

                pdfDoc.Add(new Paragraph(nextLaunch.ToString()));
                pdfDoc.Close();
                return File(stream.ToArray(), "application/pdf", "NextLaunch.pdf");
            }
        }
    }
}

CSharpSpaceXApp/Controllers/UpcomingLaunchesController.cs
using System.Collections.Generic;
using CSharpSpaceXApp.Models;
using CSharpSpaceXApp.Services.Contracts;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;
using System.Linq;
using CSharpSpaceXApp.Exceptions;


/// <summary>
/// Takes information from the SpaceX API about upcoming launches and provides it to the view.
/// </summary>
namespace CSharpSpaceXApp.Controllers
{
    public class UpcomingLaunchesController : Controller
    {
        IGitHubService gitHubService;
        private List<Launch> upcomingLaunches;


        public UpcomingLaunchesController(IGitHubService gitHubService)
        {
            this.gitHubService = gitHubService;
        }


        public IActionResult Upcoming(int? currPage)
        {
            var currentPage = currPage ?? 1;
           try
           {
               upcomingLaunches = gitHubService.GetUpcomingFlights(Constants.Constants.UPCOMING_LAUNCHES);
           } catch (APIConnectionException e)
           {
                ViewBag.Message = e.Message;
                return Redirect("APIError");

            }
           var totalPages = this.upcomingLaunches.Count - 1;

           var model = new SheduedFlight
           {
               shefuedLaunch = upcomingLaunches[currentPage],
               CurrPage = currentPage,
               TotalPages = totalPages,
           };


           if (totalPages > currentPage)
           {
               model.NextPage = currentPage + 1;
           }

           if (currentPage > 1)
           {
               model.PrevPage = currentPage - 1;
           }

           model.shefuedLaunch = GetRockets(currentPage).First();

           return View(model);
            

        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }

        private IEnumerable<Launch> GetRockets(int currentPage)
        {
            IEnumerable<Launch> currentData;

            if (currentPage == 1)
            {
                currentData = this.upcomingLaunches.Take(1);
            }
            else
            {
                currentData = upcomingLaunches
                        .Skip(currentPage - 1)
                         .Take(1);
            }
            
            return currentData;
        }

    }
}

CSharpSpaceXApp/Views/UpcomingLaunches/Upcoming.cshtml
@model SheduedFlight


@{
    ViewBag.Title = "Upcoming Launches";
    Layout = "~/Views/Shared/_Layout.cshtml";

}
<h2>Upcomming SpaceX launch plans</h2>
<br>
<br>
<br>

<body>
    <div class="space-img">
        <img src="https://i.pinimg.com/originals/05/86/00/058600c7547504c3b05ce46ef6fb901d.jpg" width="350" height="500" />
    </div>

    <pre>@Model.shefuedLaunch.ToString()</pre>

    <hr />


    @using (Html.BeginForm("ExportUpcoming", "File", FormMethod.Post))
    {
        <input type="hidden" name="Upcoming" />
        <input type="submit" id="btnSubmit" value="Export" />

    }
    <script type="text/javascript" src="http://ajax.googleapis.com/ajax/libs/jquery/1.8.3/jquery.min.js"></script>
    <script type="text/javascript">
        $(function () {
            $("#btnSubmit").click(function () {
                $("input[name='Upcoming']").val($("#Grid").html());
            });
        });
    </script>

    <br />
    <br />

    <div class="pagination">
        @if (Model.PrevPage == null)
        {
            <a class="btn btn-sm btn-lighter btn-auto disabled">Prev</a>
        }
        else
        {
            <a asp-action="Upcoming" asp-route-currPage="@Model.PrevPage" class="btn btn-sm btn-lighter btn-auto" value="@Model.PrevPage">Prev</a>
        }

        <a class="btn btn-sm btn-primary btn-auto" value="@Model.CurrPage">@Model.CurrPage</a>

        @if (Model.NextPage == null)
        {
            <a class="btn btn-sm btn-lighter btn-auto disabled">Next</a>
        }
        else
        {
            <a asp-controller="UpcomingLaunches" asp-action="Upcoming" asp-route-currPage="@Model.NextPage" class="btn btn-sm btn-lighter btn-auto" value="@Model.NextPage">Next</a>
        }
    </div>

</body>

<style>
    .custom-text {
        font-family: Candara;
        font-size: large;
        overflow-x: hidden;
    }

    .spacex-image {
        float: right
    }

    pre {
        word-wrap: break-word; 
        white-space: pre-wrap; 
        text-align: justify
    }

    .pagination{
        margin-left: 450px;
    }
    .space-img {
        float: right;
        margin: 10px;
    }
</style>